fullnameOverride: calico

serviceAccount:
  create: true

podSecurityPolicy:
  create: false

calico:
  tag: v3.19.2

  typha:
    logseverity: Info   # Debug, Info, Warning, Error, Fatal
    image: calico/typha
    # Controls a PodDisruptionBudget for the Typha pod. Suggested use if having one always running
    podDisruptionBudget:
      enabled: true
      # minAvailable: 1
      maxUnavailable: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "96Mi"
        cpu: "100m"
    tolerations: []
    nodeSelector:
      beta.kubernetes.io/os: linux
    podAnnotations: {}
  node:
    logseverity: Info   # Debug, Info, Warning, Error, Fatal
    image: calico/node
    resources:
      requests:
        memory: "32Mi"
        cpu: "20m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    extraEnv: []
    # - name: SOME_VAR
    #   value: 'some value'
    nodeSelector:
      beta.kubernetes.io/os: linux
    podAnnotations: {}
  typha_autoscaler:
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "10m"
    tolerations: []
    nodeSelector:
      beta.kubernetes.io/os: linux
    podAnnotations: {}

autoscaler:
  tag: "1.8.5"
  image: k8s.gcr.io/cpa/cluster-proportional-autoscaler
  configData:
    ladder: |-
      {
        "coresToReplicas": [],
        "nodesToReplicas": [
          [1, 1],
          [10, 2],
          [100, 3],
          [250, 4],
          [500, 5],
          [1000, 6],
          [1500, 7],
          [2000, 8]
        ]
      }
