kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-horizontal-autoscaler"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
{{- with .Values.autoscaler.configData }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
