kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-horizontal-autoscaler"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
data:
  ladder: |-
    {
      "coresToReplicas": {{ .Values.autoscaler.coresToReplicas  | quote }},
      "nodesToReplicas": {{ .Values.autoscaler.nodesToReplicas  | quote }}
    }
