# This manifest creates a Pod Disruption Budget for Typha to allow K8s Cluster Autoscaler to evict
{{- if .Values.calico.typha.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha"
  labels:
    app.kubernetes.io/name: "{{ include "aws-calico.fullname" . }}-typha"
{{ include "aws-calico.labels" . | indent 4 }}
spec:
{{- if .Values.calico.typha.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.calico.typha.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.calico.typha.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.calico.typha.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "aws-calico.fullname" . }}-typha"
{{- end }}
