name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "stable/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.6.0
        with:
          command: lint
          config: .github/ct.yaml
